function make
c = computer;
switch c
    case 'MACI64'
        mex -O -largeArrayDims -I../include -I../libmetis ...
                -I../GKlib -L../build/Darwin-x86_64/libmetis ...
                -lmetis metismex.c -D__thread= -DLINUX
    case 'GLNX64'
        mex -O -largeArrayDims -I../include -I../libmetis ...
                -I../GKlib -L../build/Linux-x86_64/libmetis ...
                -lmetis metismex.c -DLINUX
    case 'MACI64'
        mex -O -largeArrayDims -I../include -I../libmetis ...
                -I../GKlib -L../build/Darwin-x86/libmetis ...
                -lmetis metismex.c -D__thread= -DLINUX
    case 'GLNX64'
        mex -O -largeArrayDims -I../include -I../libmetis ...
                -I../GKlib -L../build/Linux-x86/libmetis ...
                -lmetis metismex.c -DLINUX
end
test_main